"""Adicionando location_id no model item para facilitar saber qual é a localização atual do item

Revision ID: 03d9a805f1a8
Revises: a9dbe1fd1e2d
Create Date: 2025-08-30 17:41:26.775144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d9a805f1a8'
down_revision: Union[str, Sequence[str], None] = 'a9dbe1fd1e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_item', sa.Column(
        'location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_logistic_stock_item_location_id'),
                    'logistic_stock_item', ['location_id'], unique=False)
    op.create_foreign_key(None, 'logistic_stock_item',
                          'logistica_groupaditionalinformation', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logistic_stock_item', type_='foreignkey')
    op.drop_index(op.f('ix_logistic_stock_item_location_id'),
                  table_name='logistic_stock_item')
    op.drop_column('logistic_stock_item', 'location_id')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_type'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
