"""Permitindo duplicar o serial

Revision ID: 1863ddff6985
Revises: 341020a46b66
Create Date: 2026-02-13 22:32:57.146278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1863ddff6985'
down_revision: Union[str, Sequence[str], None] = '341020a46b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index(op.f('ix_logistic_stock_errors_serial'),
                  table_name='logistic_stock_errors')
    op.create_index(op.f('ix_logistic_stock_errors_serial'),
                    'logistic_stock_errors', ['serial'], unique=False)
    op.drop_index(op.f('ix_item_extra_ztipo'), table_name='logistic_stock_item',
                  postgresql_where="(((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text) IS NOT NULL)")
    op.create_index('ix_item_extra_ztipo', 'logistic_stock_item', [sa.literal_column(
        "(extra_info -> 'consulta_sincrona' ->> 'ZTIPO')")], unique=False, postgresql_where=sa.text("(extra_info -> 'consulta_sincrona' ->> 'ZTIPO') IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_extra_ztipo', table_name='logistic_stock_item', postgresql_where=sa.text(
        "(extra_info -> 'consulta_sincrona' ->> 'ZTIPO') IS NOT NULL"))
    op.create_index(op.f('ix_item_extra_ztipo'), 'logistic_stock_item', [sa.literal_column(
        "((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text)")], unique=False, postgresql_where="(((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text) IS NOT NULL)")
    op.drop_index(op.f('ix_logistic_stock_errors_serial'),
                  table_name='logistic_stock_errors')
    op.create_index(op.f('ix_logistic_stock_errors_serial'),
                    'logistic_stock_errors', ['serial'], unique=True)
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
