"""criado novo model para controlar o campo origin

Revision ID: 5ab293fc26a6
Revises: 7159a6140395
Create Date: 2025-08-30 13:54:16.760674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab293fc26a6'
down_revision: Union[str, Sequence[str], None] = '7159a6140395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_stock_movement_product_id'),
                  table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_order_origin'),
                  table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_order_number'),
                  table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_movement_type'),
                  table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_kit_number'),
                  table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_item_id'),
                  table_name='logistic_stock_movement')
    op.drop_table('logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_item_serial'),
                  table_name='logistic_stock_item')
    op.drop_index(op.f('ix_logistic_stock_item_product_id'),
                  table_name='logistic_stock_item')
    op.drop_table('logistic_stock_item')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_type'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistic_stock_product_sku'),
                  table_name='logistic_stock_product')
    op.drop_index(op.f('ix_logistic_stock_product_description'),
                  table_name='logistic_stock_product')
    op.drop_index(op.f('ix_logistic_stock_product_category'),
                  table_name='logistic_stock_product')
    op.drop_table('logistic_stock_product')
    # ### end Alembic commands ###
