"""Ajustada validação do model de origin para aceitar project e origin iguais desde que stock_type diferente

Revision ID: 60d70b20d175
Revises: d8091ba820b4
Create Date: 2025-12-12 21:17:56.158518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d70b20d175'
down_revision: Union[str, Sequence[str], None] = 'd8091ba820b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_origin_name_project'),
                  table_name='logistic_stock_order_origin')
    op.create_index('ix_origin_name_project', 'logistic_stock_order_origin', [
                    'origin_name', 'project_name', 'stock_type'], unique=False)
    op.drop_constraint(op.f('uq_origin_business_key'),
                       'logistic_stock_order_origin', type_='unique')
    op.create_unique_constraint('uq_origin_business_key', 'logistic_stock_order_origin', [
                                'origin_name', 'project_name', 'client_id', 'stock_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_origin_business_key',
                       'logistic_stock_order_origin', type_='unique')
    op.create_unique_constraint(op.f('uq_origin_business_key'), 'logistic_stock_order_origin', [
                                'origin_name', 'project_name', 'client_id'])
    op.drop_index('ix_origin_name_project',
                  table_name='logistic_stock_order_origin')
    op.create_index(op.f('ix_origin_name_project'), 'logistic_stock_order_origin', [
                    'origin_name', 'project_name'], unique=False)
