"""tornando campo product_id como opicional

Revision ID: 7159a6140395
Revises: acdcc0403cbb
Create Date: 2025-08-30 13:41:42.031842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7159a6140395'
down_revision: Union[str, Sequence[str], None] = 'acdcc0403cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_stock_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_stock_product_category'), 'logistic_stock_product', ['category'], unique=False)
    op.create_index(op.f('ix_logistic_stock_product_description'), 'logistic_stock_product', ['description'], unique=False)
    op.create_index(op.f('ix_logistic_stock_product_sku'), 'logistic_stock_product', ['sku'], unique=True)
    op.create_table('logistic_stock_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['logistic_stock_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_stock_item_product_id'), 'logistic_stock_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_logistic_stock_item_serial'), 'logistic_stock_item', ['serial'], unique=True)
    op.create_table('logistic_stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUST', 'RETURN', 'PICK', 'PACK', name='movementtype'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('order_origin', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.Column('kit_number', sa.String(), nullable=True),
    sa.Column('extra_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['logistica_groupaditionalinformation.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['logistic_stock_item.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['logistic_stock_product.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['logistica_groupaditionalinformation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_stock_movement_item_id'), 'logistic_stock_movement', ['item_id'], unique=False)
    op.create_index(op.f('ix_logistic_stock_movement_kit_number'), 'logistic_stock_movement', ['kit_number'], unique=False)
    op.create_index(op.f('ix_logistic_stock_movement_movement_type'), 'logistic_stock_movement', ['movement_type'], unique=False)
    op.create_index(op.f('ix_logistic_stock_movement_order_number'), 'logistic_stock_movement', ['order_number'], unique=False)
    op.create_index(op.f('ix_logistic_stock_movement_order_origin'), 'logistic_stock_movement', ['order_origin'], unique=False)
    op.create_index(op.f('ix_logistic_stock_movement_product_id'), 'logistic_stock_movement', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_stock_movement_product_id'), table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_order_origin'), table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_order_number'), table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_movement_type'), table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_kit_number'), table_name='logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_movement_item_id'), table_name='logistic_stock_movement')
    op.drop_table('logistic_stock_movement')
    op.drop_index(op.f('ix_logistic_stock_item_serial'), table_name='logistic_stock_item')
    op.drop_index(op.f('ix_logistic_stock_item_product_id'), table_name='logistic_stock_item')
    op.drop_table('logistic_stock_item')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_type'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'), table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'), table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistic_stock_product_sku'), table_name='logistic_stock_product')
    op.drop_index(op.f('ix_logistic_stock_product_description'), table_name='logistic_stock_product')
    op.drop_index(op.f('ix_logistic_stock_product_category'), table_name='logistic_stock_product')
    op.drop_table('logistic_stock_product')
    # ### end Alembic commands ###
