"""Criado model separado de RomaneioItem

Revision ID: 8b786954b5a0
Revises: f33f01ddfe75
Create Date: 2025-09-18 11:16:59.009988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b786954b5a0'
down_revision: Union[str, Sequence[str], None] = 'f33f01ddfe75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_stock_reverse',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('status_rom', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('update_at', sa.DateTime(), nullable=True),
                    sa.Column('update_by', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_logistic_stock_reverse_status_rom'),
                    'logistic_stock_reverse', ['status_rom'], unique=False)
    op.add_column('logistic_stock_reverse_item', sa.Column(
        'romaneio_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_logistic_stock_reverse_item_status_rom'),
                  table_name='logistic_stock_reverse_item')
    op.create_index(op.f('ix_logistic_stock_reverse_item_romaneio_id'),
                    'logistic_stock_reverse_item', ['romaneio_id'], unique=False)
    op.create_foreign_key(None, 'logistic_stock_reverse_item',
                          'logistic_stock_reverse', ['romaneio_id'], ['id'])
    op.drop_column('logistic_stock_reverse_item', 'status_rom')
    op.drop_column('logistic_stock_reverse_item', 'update_by')
    op.drop_column('logistic_stock_reverse_item', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_stock_reverse_item', sa.Column(
        'update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('logistic_stock_reverse_item', sa.Column(
        'update_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logistic_stock_reverse_item', sa.Column(
        'status_rom', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'logistic_stock_reverse_item', type_='foreignkey')
    op.drop_index(op.f('ix_logistic_stock_reverse_item_romaneio_id'),
                  table_name='logistic_stock_reverse_item')
    op.create_index(op.f('ix_logistic_stock_reverse_item_status_rom'),
                    'logistic_stock_reverse_item', ['status_rom'], unique=False)
    op.drop_column('logistic_stock_reverse_item', 'romaneio_id')
    op.drop_index(op.f('ix_logistic_stock_reverse_status_rom'),
                  table_name='logistic_stock_reverse')
    op.drop_table('logistic_stock_reverse')
    # ### end Alembic commands ###
