"""Criado model para os seriais provisórios/ilegíveis

Revision ID: a51ad7e04794
Revises: 311badb0468d
Create Date: 2026-01-08 12:38:45.598016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51ad7e04794'
down_revision: Union[str, Sequence[str], None] = '311badb0468d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('logistic_stock_item_provisional_serial',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('new_serial_number',
                              sa.String(), nullable=False),
                    sa.Column('old_serial_number', sa.String(), nullable=True),
                    sa.Column('reason', sa.String(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['logistic_stock_item.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'new_serial_number', name='uix_logistic_stock_item_provisional_serial_new_serial_number')
                    )
    op.create_index(op.f('ix_logistic_stock_item_provisional_serial_item_id'),
                    'logistic_stock_item_provisional_serial', ['item_id'], unique=False)
    op.create_index(op.f('ix_logistic_stock_item_provisional_serial_new_serial_number'),
                    'logistic_stock_item_provisional_serial', ['new_serial_number'], unique=False)
    op.create_index(op.f('ix_logistic_stock_item_provisional_serial_old_serial_number'),
                    'logistic_stock_item_provisional_serial', ['old_serial_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_stock_item_provisional_serial_old_serial_number'),
                  table_name='logistic_stock_item_provisional_serial')
    op.drop_index(op.f('ix_logistic_stock_item_provisional_serial_new_serial_number'),
                  table_name='logistic_stock_item_provisional_serial')
    op.drop_index(op.f('ix_logistic_stock_item_provisional_serial_item_id'),
                  table_name='logistic_stock_item_provisional_serial')
    op.drop_table('logistic_stock_item_provisional_serial')
    # ### end Alembic commands ###
