"""Adicionado relacionamento com model de client

Revision ID: ade4ca07f365
Revises: 9b71719b92ea
Create Date: 2025-09-26 12:57:55.605427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade4ca07f365'
down_revision: Union[str, Sequence[str], None] = '9b71719b92ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_order_origin', sa.Column(
        'client_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_logistic_stock_order_origin_client_name'),
                  table_name='logistic_stock_order_origin')
    op.drop_constraint(op.f('uq_origin_business_key'),
                       'logistic_stock_order_origin', type_='unique')
    op.create_unique_constraint('uq_origin_business_key', 'logistic_stock_order_origin', [
                                'origin_name', 'project_name', 'client_id'])
    op.create_foreign_key(None, 'logistic_stock_order_origin',
                          'logistic_stock_client', ['client_id'], ['id'])
    op.drop_column('logistic_stock_order_origin', 'client_name')
    op.add_column('logistic_stock_product', sa.Column(
        'client_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_logistic_stock_product_client_name'),
                  table_name='logistic_stock_product')
    op.create_foreign_key(None, 'logistic_stock_product',
                          'logistic_stock_client', ['client_id'], ['id'])
    op.drop_column('logistic_stock_product', 'client_name')
    op.alter_column(
        'logistic_stock_reverse',
        'client_id',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="client_id::integer"
    )
    op.create_foreign_key(None, 'logistic_stock_reverse',
                          'logistic_stock_client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logistic_stock_reverse', type_='foreignkey')
    op.alter_column('logistic_stock_reverse', 'client_id',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.add_column('logistic_stock_product', sa.Column(
        'client_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'logistic_stock_product', type_='foreignkey')
    op.create_index(op.f('ix_logistic_stock_product_client_name'),
                    'logistic_stock_product', ['client_name'], unique=False)
    op.drop_column('logistic_stock_product', 'client_id')
    op.add_column('logistic_stock_order_origin', sa.Column(
        'client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'logistic_stock_order_origin', type_='foreignkey')
    op.drop_constraint('uq_origin_business_key',
                       'logistic_stock_order_origin', type_='unique')
    op.create_unique_constraint(op.f('uq_origin_business_key'), 'logistic_stock_order_origin', [
                                'origin_name', 'project_name', 'client_name'])
    op.create_index(op.f('ix_logistic_stock_order_origin_client_name'),
                    'logistic_stock_order_origin', ['client_name'], unique=False)
    op.drop_column('logistic_stock_order_origin', 'client_id')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
