"""Tornando campo de origem e destino opcionais

Revision ID: b26c3f7dd0c2
Revises: a51ad7e04794
Create Date: 2026-01-28 15:37:41.981614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26c3f7dd0c2'
down_revision: Union[str, Sequence[str], None] = 'a51ad7e04794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_stock_reverse', sa.Column(
        'origin_id', sa.Integer(), nullable=True))
    op.add_column('logistic_stock_reverse', sa.Column(
        'destination_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logistic_stock_reverse',
                          'logistica_groupaditionalinformation', ['destination_id'], ['id'])
    op.create_foreign_key(None, 'logistic_stock_reverse',
                          'logistica_groupaditionalinformation', ['origin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logistic_stock_reverse', type_='foreignkey')
    op.drop_constraint(None, 'logistic_stock_reverse', type_='foreignkey')
    op.drop_column('logistic_stock_reverse', 'destination_id')
    op.drop_column('logistic_stock_reverse', 'origin_id')
