"""Tentando atualizar movementtype

Revision ID: b45c69a0692b
Revises: 5908c89b0ec3
Create Date: 2025-08-30 20:10:28.431529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45c69a0692b'
down_revision: Union[str, Sequence[str], None] = '5908c89b0ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
