"""Adicionado novo campo na tabela de erros

Revision ID: b53f1d72e13c
Revises: e6910bc13c55
Create Date: 2026-03-04 09:46:21.606367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53f1d72e13c'
down_revision: Union[str, Sequence[str], None] = 'e6910bc13c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_stock_errors', sa.Column(
        'resolved_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('logistic_stock_errors', 'resolved_message')
