"""Criado novo model para controlar os romaneios gerados

Revision ID: b60c3f44406a
Revises: c0d89e05e6d2
Create Date: 2025-09-17 18:38:43.429423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60c3f44406a'
down_revision: Union[str, Sequence[str], None] = 'c0d89e05e6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_stock_reverse_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.String(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('volume_number', sa.String(), nullable=False),
                    sa.Column('kit_number', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['logistic_stock_item.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_logistic_stock_reverse_item_item_id'),
                    'logistic_stock_reverse_item', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_stock_reverse_item_item_id'),
                  table_name='logistic_stock_reverse_item')
    op.drop_table('logistic_stock_reverse_item')

    # ### end Alembic commands ###
