"""Criado novo model para controlar os romaneios gerados

Revision ID: c0d89e05e6d2
Revises: ef385babe054
Create Date: 2025-09-17 18:36:33.335644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d89e05e6d2'
down_revision: Union[str, Sequence[str], None] = 'ef385babe054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
