"""Adicionando campo de stock_type na tabela de origin

Revision ID: d8091ba820b4
Revises: fc5d44ae7c3f
Create Date: 2025-12-12 21:11:48.800693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8091ba820b4'
down_revision: Union[str, Sequence[str], None] = 'fc5d44ae7c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_order_origin', sa.Column(
        'stock_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistic_stock_order_origin', 'stock_type')

    # ### end Alembic commands ###
