"""Alterado model para permitir salvar location_id como None

Revision ID: e6910bc13c55
Revises: 1863ddff6985
Create Date: 2026-02-16 11:29:46.616448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6910bc13c55'
down_revision: Union[str, Sequence[str], None] = '1863ddff6985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('logistic_stock_errors', 'location_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_extra_ztipo', table_name='logistic_stock_item', postgresql_where=sa.text(
        "(extra_info -> 'consulta_sincrona' ->> 'ZTIPO') IS NOT NULL"))
    op.create_index(op.f('ix_item_extra_ztipo'), 'logistic_stock_item', [sa.literal_column(
        "((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text)")], unique=False, postgresql_where="(((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text) IS NOT NULL)")
    op.alter_column('logistic_stock_errors', 'location_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
