"""Adicionado Order origin e mapeado em movements

Revision ID: 38a4a56def49
Revises: ee3760f8e591
Create Date: 2025-08-30 14:03:31.679935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a4a56def49'
down_revision: Union[str, Sequence[str], None] = 'ee3760f8e591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_stock_order_origin',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('client_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('project_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('origin_name', sa.String(
                        length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('origin_name', 'project_name',
                                        'client_name', name='uq_origin_business_key')
                    )
    op.create_index(op.f('ix_logistic_stock_order_origin_client_name'),
                    'logistic_stock_order_origin', ['client_name'], unique=False)
    op.create_index(op.f('ix_logistic_stock_order_origin_id'),
                    'logistic_stock_order_origin', ['id'], unique=False)
    op.create_index(op.f('ix_logistic_stock_order_origin_origin_name'),
                    'logistic_stock_order_origin', ['origin_name'], unique=False)
    op.create_index(op.f('ix_logistic_stock_order_origin_project_name'),
                    'logistic_stock_order_origin', ['project_name'], unique=False)
    op.create_index('ix_origin_name_project', 'logistic_stock_order_origin', [
                    'origin_name', 'project_name'], unique=False)
    op.add_column('logistic_stock_movement', sa.Column(
        'order_origin_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_logistic_stock_movement_order_origin'),
                  table_name='logistic_stock_movement')
    op.create_index(op.f('ix_logistic_stock_movement_order_origin_id'),
                    'logistic_stock_movement', ['order_origin_id'], unique=False)
    op.create_foreign_key(None, 'logistic_stock_movement',
                          'logistic_stock_order_origin', ['order_origin_id'], ['id'])
    op.drop_column('logistic_stock_movement', 'order_origin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_stock_movement', sa.Column(
        'order_origin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'logistic_stock_movement', type_='foreignkey')
    op.drop_index(op.f('ix_logistic_stock_movement_order_origin_id'),
                  table_name='logistic_stock_movement')
    op.create_index(op.f('ix_logistic_stock_movement_order_origin'),
                    'logistic_stock_movement', ['order_origin'], unique=False)
    op.drop_column('logistic_stock_movement', 'order_origin_id')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_type'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    op.drop_index('ix_origin_name_project',
                  table_name='logistic_stock_order_origin')
    op.drop_index(op.f('ix_logistic_stock_order_origin_project_name'),
                  table_name='logistic_stock_order_origin')
    op.drop_index(op.f('ix_logistic_stock_order_origin_origin_name'),
                  table_name='logistic_stock_order_origin')
    op.drop_index(op.f('ix_logistic_stock_order_origin_id'),
                  table_name='logistic_stock_order_origin')
    op.drop_index(op.f('ix_logistic_stock_order_origin_client_name'),
                  table_name='logistic_stock_order_origin')
    op.drop_table('logistic_stock_order_origin')
    # ### end Alembic commands ###
