"""Criado model de cliente

Revision ID: 4009ff442468
Revises: df11f928135e
Create Date: 2025-09-26 12:17:33.351609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4009ff442468'
down_revision: Union[str, Sequence[str], None] = 'df11f928135e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_stock_client',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('client_code', sa.String(), nullable=False),
                    sa.Column('client_name', sa.String(), nullable=True),
                    sa.Column('created_by', sa.String(), nullable=True),
                    sa.Column('extra_info', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_logistic_stock_client_client_code'),
                    'logistic_stock_client', ['client_code'], unique=True)
    op.create_index(op.f('ix_logistic_stock_client_client_name'),
                    'logistic_stock_client', ['client_name'], unique=False)
    op.add_column('logistic_stock_reverse', sa.Column(
        'client_id', sa.String(), nullable=True))
    op.add_column('logistic_stock_reverse', sa.Column(
        'romaneio_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_logistic_stock_reverse_romaneio_number'),
                    'logistic_stock_reverse', ['romaneio_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_stock_reverse_romaneio_number'),
                  table_name='logistic_stock_reverse')
    op.drop_column('logistic_stock_reverse', 'romaneio_number')
    op.drop_column('logistic_stock_reverse', 'client_id')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistic_stock_client_client_name'),
                  table_name='logistic_stock_client')
    op.drop_index(op.f('ix_logistic_stock_client_client_code'),
                  table_name='logistic_stock_client')
    op.drop_table('logistic_stock_client')
    # ### end Alembic commands ###
