"""ainda tentando atualizar movementtype

Revision ID: 42032025d209
Revises: 7da16f6c885e
Create Date: 2025-08-30 20:20:25.097594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42032025d209'
down_revision: Union[str, Sequence[str], None] = '7da16f6c885e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logistic_stock_item', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_index(op.f('ix_logistic_stock_item_status'),
                    'logistic_stock_item', ['status'], unique=False)
    op.alter_column('logistic_stock_movement', 'movement_type',
                    existing_type=postgresql.ENUM(
                        'IN', 'OUT', 'TRANSFER', 'ADJUST', 'RETURN', 'PICK', 'PACK', name='movementtype'),
                    type_=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logistic_stock_movement', 'movement_type',
                    existing_type=sa.String(),
                    type_=postgresql.ENUM(
                        'IN', 'OUT', 'TRANSFER', 'ADJUST', 'RETURN', 'PICK', 'PACK', name='movementtype'),
                    existing_nullable=False)
    op.drop_index(op.f('ix_logistic_stock_item_status'),
                  table_name='logistic_stock_item')
    op.alter_column('logistic_stock_item', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
