"""Adicionado novo campo na tabela de erros

Revision ID: 4483cbfaccca
Revises: 8ef2eb7da28d
Create Date: 2026-03-04 11:34:39.176346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4483cbfaccca'
down_revision: Union[str, Sequence[str], None] = '8ef2eb7da28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_stock_errors', sa.Column(
        'resolved_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('logistic_stock_errors', 'resolved_message')
