"""Criado novo model para controlar os erros de estoque

Revision ID: 4a9ceeba7fec
Revises: 319414819f6d
Create Date: 2026-02-13 21:41:32.564489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9ceeba7fec'
down_revision: Union[str, Sequence[str], None] = '319414819f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_stock_errors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('serial', sa.String(), nullable=True),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('message_error', sa.String(), nullable=False),
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.Column('error_origin', sa.String(), nullable=False),
                    sa.Column('resolved', sa.Boolean(), nullable=False),
                    sa.Column('resolved_by', sa.String(), nullable=True),
                    sa.Column('resolved_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['location_id'], ['logistica_groupaditionalinformation.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_logistic_stock_errors_location_id'),
                    'logistic_stock_errors', ['location_id'], unique=False)
    op.create_index(op.f('ix_logistic_stock_errors_serial'),
                    'logistic_stock_errors', ['serial'], unique=True)
    op.create_index(op.f('ix_logistic_stock_errors_status'),
                    'logistic_stock_errors', ['status'], unique=False)
    op.drop_index(op.f('ix_item_extra_ztipo'), table_name='logistic_stock_item',
                  postgresql_where="(((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text) IS NOT NULL)")
    op.create_index('ix_item_extra_ztipo', 'logistic_stock_item', [sa.literal_column(
        "(extra_info -> 'consulta_sincrona' ->> 'ZTIPO')")], unique=False, postgresql_where=sa.text("(extra_info -> 'consulta_sincrona' ->> 'ZTIPO') IS NOT NULL"))
    op.create_index(op.f('ix_logistic_stock_reverse_created_by'),
                    'logistic_stock_reverse', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_stock_reverse_created_by'),
                  table_name='logistic_stock_reverse')
    op.drop_index('ix_item_extra_ztipo', table_name='logistic_stock_item', postgresql_where=sa.text(
        "(extra_info -> 'consulta_sincrona' ->> 'ZTIPO') IS NOT NULL"))
    op.create_index(op.f('ix_item_extra_ztipo'), 'logistic_stock_item', [sa.literal_column(
        "((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text)")], unique=False, postgresql_where="(((extra_info -> 'consulta_sincrona'::text) ->> 'ZTIPO'::text) IS NOT NULL)")
    op.drop_index(op.f('ix_logistic_stock_errors_status'),
                  table_name='logistic_stock_errors')
    op.drop_index(op.f('ix_logistic_stock_errors_serial'),
                  table_name='logistic_stock_errors')
    op.drop_index(op.f('ix_logistic_stock_errors_location_id'),
                  table_name='logistic_stock_errors')
    op.drop_table('logistic_stock_errors')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
