"""Adicionando campo de stock_type na tabela de origin

Revision ID: 732a97af967d
Revises: b328195fe89b
Create Date: 2025-12-12 21:12:34.147310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732a97af967d'
down_revision: Union[str, Sequence[str], None] = 'b328195fe89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_order_origin', sa.Column(
        'stock_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistic_stock_order_origin', 'stock_type')

    # ### end Alembic commands ###
