"""Adicionado campo de order_number em RomaneioItem

Revision ID: 79304a53f5e1
Revises: 1870ff705855
Create Date: 2025-09-18 13:45:57.107141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79304a53f5e1'
down_revision: Union[str, Sequence[str], None] = '1870ff705855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_reverse_item', sa.Column(
        'order_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistic_stock_reverse_item', 'order_number')
