"""Ajustada validação do model de origin para aceitar project e origin iguais desde que stock_type diferente

Revision ID: 79dbeb440274
Revises: 732a97af967d
Create Date: 2025-12-12 21:17:05.438613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79dbeb440274'
down_revision: Union[str, Sequence[str], None] = '732a97af967d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_origin_name_project'),
                  table_name='logistic_stock_order_origin')
    op.create_index('ix_origin_name_project', 'logistic_stock_order_origin', [
                    'origin_name', 'project_name', 'stock_type'], unique=False)
    op.drop_constraint(op.f('uq_origin_business_key'),
                       'logistic_stock_order_origin', type_='unique')
    op.create_unique_constraint('uq_origin_business_key', 'logistic_stock_order_origin', [
                                'origin_name', 'project_name', 'client_id', 'stock_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_origin_business_key',
                       'logistic_stock_order_origin', type_='unique')
    op.create_unique_constraint(op.f('uq_origin_business_key'), 'logistic_stock_order_origin', [
                                'origin_name', 'project_name', 'client_id'])
    op.drop_index('ix_origin_name_project',
                  table_name='logistic_stock_order_origin')
    op.create_index(op.f('ix_origin_name_project'), 'logistic_stock_order_origin', [
                    'origin_name', 'project_name'], unique=False)

    # ### end Alembic commands ###
