"""Adicionados campos de origem e destino no romaneio

Revision ID: 81f20659cdb4
Revises: 8007c7349875
Create Date: 2026-01-28 15:34:52.338108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f20659cdb4'
down_revision: Union[str, Sequence[str], None] = '8007c7349875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_reverse', sa.Column(
        'origin_id', sa.Integer(), nullable=True))
    op.add_column('logistic_stock_reverse', sa.Column(
        'destination_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logistic_stock_reverse',
                          'logistica_groupaditionalinformation', ['origin_id'], ['id'])
    op.create_foreign_key(None, 'logistic_stock_reverse',
                          'logistica_groupaditionalinformation', ['destination_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logistic_stock_reverse', type_='foreignkey')
    op.drop_constraint(None, 'logistic_stock_reverse', type_='foreignkey')
    op.drop_column('logistic_stock_reverse', 'destination_id')
    op.drop_column('logistic_stock_reverse', 'origin_id')
