"""Adicionadas colunas: status_rom, updated_at e updated_by

Revision ID: 8cf0f132372d
Revises: 169be7a085c0
Create Date: 2025-09-18 10:45:36.360691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf0f132372d'
down_revision: Union[str, Sequence[str], None] = '169be7a085c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_reverse_item', sa.Column(
        'status_rom', sa.String(), nullable=False))
    op.add_column('logistic_stock_reverse_item', sa.Column(
        'update_at', sa.DateTime(), nullable=True))
    op.add_column('logistic_stock_reverse_item', sa.Column(
        'update_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_logistic_stock_reverse_item_status_rom'),
                    'logistic_stock_reverse_item', ['status_rom'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_stock_reverse_item_status_rom'),
                  table_name='logistic_stock_reverse_item')
    op.drop_column('logistic_stock_reverse_item', 'update_by')
    op.drop_column('logistic_stock_reverse_item', 'update_at')
    op.drop_column('logistic_stock_reverse_item', 'status_rom')
