"""criada relação entre item e movimento para facilitar consultas futuras

Revision ID: b328195fe89b
Revises: 6439ae41756d
Create Date: 2025-11-06 19:34:22.084293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b328195fe89b'
down_revision: Union[str, Sequence[str], None] = '6439ae41756d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('logistic_stock_item', sa.Column(
        'last_in_movement_id', sa.Integer(), nullable=True))
    op.add_column('logistic_stock_item', sa.Column(
        'last_out_movement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logistic_stock_item', 'logistic_stock_movement', [
                          'last_out_movement_id'], ['id'])
    op.create_foreign_key(None, 'logistic_stock_item', 'logistic_stock_movement', [
                          'last_in_movement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logistic_stock_item', type_='foreignkey')
    op.drop_constraint(None, 'logistic_stock_item', type_='foreignkey')
    op.drop_column('logistic_stock_item', 'last_out_movement_id')
    op.drop_column('logistic_stock_item', 'last_in_movement_id')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
