"""tornando campo product_id como opicional

Revision ID: c50314132e5e
Revises: 2a61cbbf58e7
Create Date: 2025-08-30 13:46:29.656488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50314132e5e'
down_revision: Union[str, Sequence[str], None] = '2a61cbbf58e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('logistic_stock_item', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('logistic_stock_movement', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logistic_stock_movement', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('logistic_stock_item', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_type'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
