"""Removido product_id de movement

Revision ID: c7dc31462db7
Revises: 8d0394a14516
Create Date: 2025-08-30 19:53:57.781868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7dc31462db7'
down_revision: Union[str, Sequence[str], None] = '8d0394a14516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('logistic_stock_item', 'location_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_index(op.f('ix_logistic_stock_movement_product_id'),
                  table_name='logistic_stock_movement')
    op.drop_constraint(op.f('logistic_stock_movement_product_id_fkey'),
                       'logistic_stock_movement', type_='foreignkey')
    op.drop_column('logistic_stock_movement', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_stock_movement', sa.Column(
        'product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('logistic_stock_movement_product_id_fkey'),
                          'logistic_stock_movement', 'logistic_stock_product', ['product_id'], ['id'])
    op.create_index(op.f('ix_logistic_stock_movement_product_id'),
                    'logistic_stock_movement', ['product_id'], unique=False)
    op.alter_column('logistic_stock_item', 'location_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
