"""Adicionado relacionamento com a tabela de location

Revision ID: df11f928135e
Revises: 79304a53f5e1
Create Date: 2025-09-23 17:39:45.464107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df11f928135e'
down_revision: Union[str, Sequence[str], None] = '79304a53f5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistic_stock_reverse', sa.Column(
        'location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logistic_stock_reverse',
                          'logistica_groupaditionalinformation', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logistic_stock_reverse', type_='foreignkey')
    op.drop_column('logistic_stock_reverse', 'location_id')
