"""criado novo model para controlar o campo origin

Revision ID: ee3760f8e591
Revises: c50314132e5e
Create Date: 2025-08-30 13:54:07.090796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3760f8e591'
down_revision: Union[str, Sequence[str], None] = 'c50314132e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_type'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_sales_channel'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_estado'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_email'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_deposito'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cidade'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_UF'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_CEP'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_table('logistica_groupaditionalinformation')
    # ### end Alembic commands ###
